version: 2

jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install --unsafe-perm
      - run: npm run lint
      - run: npm run coverage
      - store_artifacts:
          path: coverage/lcov-report

  publish:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install --unsafe-perm
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      - run: npm version ${CIRCLE_TAG}
      - run: npm publish

workflows:
  version: 2
  main:
    jobs:
      - test:
          filters:
            tags: { only: /.*/ }
      - publish:
          context: npm-authorized
          filters:
            branches: { ignore: /.*/ }
            tags: { only: /^v.*$/ }
